name: Test workflow

on: [push]

jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest

    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
          REMOVE_LABEL: "awaiting%20review"

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one line script
        run: echo Hello, world!
